version: '3.8'

services:
  # Base de datos MySQL
  habit_mysql:
    image: mysql:8.0
    container_name: habit_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - habit-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habit_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      habit_mysql:
        condition: service_healthy
    networks:
      - habit-network
    volumes:
      - ./backend:/app

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habit_frontend
    restart: always
    ports:
      - "4200:4200"
    networks:
      - habit-network
    volumes:
      - ./frontend/habit-app:/app
      - /app/node_modules


networks:
  habit-network:
    driver: bridge

volumes:
  mysql_data: